INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (2, 'food', 'GROUP1', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (1, 'music', 'GROUP1', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (3, 'health', 'GROUP1', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (4, 'entertainment', 'GROUP2', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (5, '#easter', 'GROUP2', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (6, 'beer', 'GROUP2', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (7, 'easter', 'GROUP3', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (8, '"Happy Easter"', 'GROUP3', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (9, '"tv series"', 'GROUP3', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (10, '"rock music"', 'GROUP4', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (11, '"pop music"', 'GROUP4', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (12, '"jazz music"', 'GROUP4', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (13, '"music bar"', 'GROUP5', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (14, '"music cafe"', 'GROUP5', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (15, '"fast food"', 'GROUP5', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (16, 'hamburger', 'GROUP6', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (17, '"burger king"', 'GROUP6', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (18, 'KFC', 'GROUP6', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (19, '"fried chicken"', 'GROUP6', -1, -1);