INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (2, 'food', 'GROUP8', -1, 852529564198866944);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (1, 'music', 'GROUP8', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (3, 'health', 'GROUP9', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (4, 'entertainment', 'GROUP9', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (5, '#easter', 'GROUP10', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (6, 'beer', 'GROUP10', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (7, 'easter', 'GROUP10', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (8, '"Happy Easter"', 'GROUP10', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (9, '"tv series"', 'GROUP10', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (10, '"rock music"', 'GROUP10', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (11, '"pop music"', 'GROUP10', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (12, '"jazz music"', 'GROUP10', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (13, '"music bar"', 'GROUP10', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (14, '"music cafe"', 'GROUP10', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (15, '"fast food"', 'GROUP7', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (16, 'hamburger', 'GROUP7', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (17, '"burger king"', 'GROUP7', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (18, 'KFC', 'GROUP7', -1, -1);
INSERT INTO public.keyword (id, keyword, keyword_group, max_id, since_id) VALUES (19, '"fried chicken"', 'GROUP7', -1, -1);