##
# Example Ansible playbook that uses the PostgreSQL module.
#
# This installs PostgreSQL on an Ubuntu system, creates a database called
# "myapp" and a user called "django" with password "mysupersecretpassword"
# with access to the "myapp" database.
#
# Source: https://github.com/ansible/ansible-examples/blob/master/language_features/postgresql.yml
---
- hosts: harvester
  become: yes
  gather_facts: no

  tasks:
  - name: install setfacl support
    become: yes
    apt: pkg=acl

  - name: ensure apt cache is up to date
    apt: update_cache=yes
  
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

- hosts: harvester
  become: yes
  become_user: postgres
  gather_facts: no

  vars:
    dbname: amost_twitter
    dbuser: twitter
    dbpassword: amost-1

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  
  - name: ensure no other user can access the database
    postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent
