---
- name: setupDatabase
  hosts: dbservers
  remote_user: ubuntu
  become_method: sudo
  become_user: root
  become: yes

  tasks:
  - name: install dependencies
    apt: name={{ item }} state=present
    with_items:
    - git
    - curl

  - name: add repository for couch
    apt_repository:
      repo: ppa:couchdb/stable
      state: present

  - name: install couchdb
    apt: name=couchdb state=present
# couchdb is now installed

      
